sudo: false
language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

allow_failures:
  - php: 7.3
  - php: 7.4snapshot

install:
  - composer self-update

before_script:
  - composer install --prefer-source -n
